language: csharp
solution: MSNumpress.sln
before_install:
  - cd src/main/csharp
  - chmod +x patch_assembly_info.sh && ./patch_assembly_info.sh
install:
  - nuget restore MSNumpress.sln
  - nuget install NUnit.ConsoleRunner -Version 3.9.0 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release MSNumpress.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./MSNumpress.Test/bin/Release/MSNumpress.Test.dll
deploy:
  skip_cleanup: true
  provider: script
  script: chmod +x deploy.sh && ./deploy.sh $NUGET_API_KEY
  on:
    branch: master
